openapi: 3.0.3
servers:
  - url: http://localhost:8080
    description: Local server
info:
  title: article api
  version: 1.0.0
paths:
  /articles:
    get:
      summary: Get articles
      operationId: getArticles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
  /artiles/{id}:
    get:
      summary: Get article by id
      operationId: getArticleById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Title
        content:
          type: string
          example: Hello world
