openapi: 3.0.3
servers:
  - url: https://api.example.com/{version}
    description: Product server
    variables:
      version:
        default: v1
        description: API version
  - url: https://dev.api.example.com/{version}
    description: Develop server
    variables:
      version:
        default: v1
        description: API version
  - url: http://localhost:4010
    description: Local mock server
info:
  title: news api
  version: 1.0.0
paths:
  /articles:
    get:
      summary: Get articles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
  /artiles/{id}:
    get:
      summary: Get article by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Title
        content:
          type: string
          example: Hello world
